# Generated by Django 2.0.7 on 2018-08-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('user_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lose', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(default='', max_length=30)),
                ('menu', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
